### ISSUE TITLE
Semester/year reset

### ISSUE THREAD

**Issue by jkkealii** [jkkealii/Service_App#10]
Need to be able to handle archiving hours from past semesters and years. ETC.

**Comment by SirSeim** [comment]
Semesters, both current and past must be handled properly

**Comment by SirSeim** [comment]
GET `/api/events?semester=true` will only get the events for the current semester
- semester is calculated based on current date relative to July 1st of the year

GET `/api/events` still works as expected, getting all events

**Comment by SirSeim** [comment]
Hours calculation still needs to be done based on current semester.

Possibly calculate based on all events, but store the past semesters separately.
